### ISSUE TITLE
Replace unirest with a library that understands semantic versioning

### ISSUE THREAD

**Issue by lenhard** [uniba-dsg/betsy#25]
Currently we use unirest for communicating JSON over HTTP. However, unirest fails to use semantic versioning (although their version numbers create the impression that they do). They implement API changes for patch version updates which tends to break the build when modifying something unrelated. This has happend twice already and is really annoying. 

We should switch to a proper HTTP library.

**Comment by simonharrer** [comment]
Has been stable for 9 months -> close.
