### ISSUE TITLE
Add camunda 7.3.0

### ISSUE THREAD

**Issue by matthiasgeiger** [uniba-dsg/betsy#29]
Reffering to the [Release Notes](http://blog.camunda.org/2015/05/camunda-bpm-730-final-released.html) the BPMN conformance should be improved:
> BPMN:
> Re-implementation of Multi Instance Loop Characteristics,
> Correct implementation of Event Subprocess,

**Comment by simonharrer** [comment]
Uploaded on SVN server for file hosting purposes.

**Comment by matthiasgeiger** [comment]
Done.

Two more supported feature tests for camunda now:
- Compensation_BoundaryEvent_SubProcess
- Signal_StartEvent_EventSubProcess_Interrupting

Interestingly, nothing (directly) related to the mentioned aspects in the Release notes...
