### ISSUE TITLE
activiti v6

### ISSUE THREAD

**Issue by simonharrer** [uniba-dsg/betsy#30]
In a few days, activiti v6 will be released http://www.jorambarrez.be/blog/2015/05/20/launching-activiti-version-6-in-paris-june-10th/

**Comment by matthiasgeiger** [comment]
... still few days to go ;-) 
But in the meantime activiti 5.18 has been released...

**Comment by simonharrer** [comment]
A beta-1 release is available now for activiti6

**Comment by lenhard** [comment]
I'd still wait for the first stable release, though. Otherwise, we might just end up filing bug reports for them. 

But if you want to start with the integration, go ahead!

**Comment by simonharrer** [comment]
beta 1 is integrated b5662e55cb18a0059b7f30c406bb82a946b3021e

**Comment by simonharrer** [comment]
beta 2 released http://www.jorambarrez.be/blog/2015/12/23/activiti-6-0-0-beta2-released/
