### ISSUE TITLE
Speed up jBPM tests

### ISSUE THREAD

**Issue by matthiasgeiger** [uniba-dsg/betsy#44]
Running the `ALL ALL` command with 3 different jBPM versions and a build time of over 20h is crap... 

I already talked with Simon about the possibility to speed up the tests somehow. One possibility would be we zip the result of the installation and use this clean installation on all further tests which at least reduces the time which is needed to build and deploy the jBPM wars on wildfly.

Potential problems: During installation and uninstallation some things are added/removed to the user directory - we have to check carefully what exactly happens here and whether this might cause problems.

**Comment by simonharrer** [comment]
With Docker this is already possible.
