### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by lenhard** [uniba-dsg/betsy#87]
It seems that the travis build no longer works, because the JDK download fails:
```
Connecting to download.oracle.com (download.oracle.com)|23.215.130.114|:80... connected.

HTTP request sent, awaiting response... 404 Not Found

2017-08-11 09:09:18 ERROR 404: Not Found.

download failed

Oracle JDK 7 is NOT installed.
```
It's not too critical, since the tool works anyway, but the "build status: error" badge is not very nice on the front page. To leave the project in a more beautiful state, I suggest one of the following:
 - Repair the travis build (hands-up anyone?)
 - Alternative quickfix: Remove the travis badge

Any thoughts on this?

**Comment by simonharrer** [comment]
Removed

```
[![Build Status](https://travis-ci.org/uniba-dsg/betsy.png?branch=master)](https://travis-ci.org/uniba-dsg/betsy)
```

Can be added later if necessary.
